### ISSUE TITLE
File not downloading

### ISSUE THREAD

**Issue by pratikroy107** [keotl/pdf-colour-invert#10]
The file cannot be printed.
It's showing server error.
Please fix it.
It's Printable but not downloadable...

**Comment by keotl** [comment]
Hi, I have pushed a fix for the website. Feel free to reopen this issue if the problem happens again.

Cheers

**Comment by alb-p** [comment]
Hi @keotl , files are still printable but when I try to download them a "Failed - Network error" is displayed.

**Comment by keotl** [comment]
Hello @alb-p, could you try again and see whether the issue still occurs? I have a limit set on the website for very large PDFs which could cause a seemingly random network error. Feel free to open a new issue if you are still having trouble and we'll investigate it further.

**Comment by alb-p** [comment]
That is exactly what happened, it works fine with smaller files! Thanks for explanation @keotl
