### ISSUE TITLE
"An error occurred while handling this request"

### ISSUE THREAD

**Issue by andrewrphillips** [keotl/pdf-colour-invert#5]
Hi there! Love your site and use it all the time. This morning, I've tried to invert multiple PDFs and each time received this message. Consistent across Safari, Chrome, and Firefox. I'm running OSX 10.15.1.

Please let me know if you need any more information.

**Comment by keotl** [comment]
Hey, the site should be back to normal. Feel free to reopen this issue if the problem happens again in the future.

Cheers
